[package]
name = "goog-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
google-cloud-storage = { package="gcloud-storage", version="1.0.0" }
tokio = { version = "1.32", features = ["full", "macros"] }
